### ISSUE TITLE
DGM lib for Ubuntu

### ISSUE THREAD

**Issue by marcoippolito** [Project-10/DGM#1]
Hi,
are there any plans to port DGM library to Ubuntu?

**Comment by ereator** [comment]
Hi, 
at the moment, we do not plan to port DGM to Linux OS, however it is theoretically possible in the future. 
Please check the corresponding topic on our forum for the latest progress in this direction: [DGM lib for Ubuntu](http://project-10.de/forum/viewtopic.php?f=31&t=962&sid=1789d0226858353f052700ba234b6a3d)

**Comment by ereator** [comment]
Please use the following commands to build the library for Ubuntu:

`mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/usr/local 
make
make install
make clean`

@marcoippolito If you have no further problem building the DGM library for Ubuntu, please close this issue.
