### ISSUE TITLE
I modified everything to work with upcoming OpenCV 4. changes

### ISSUE THREAD

**Issue by TechnikEmpire** [Project-10/DGM#15]
Do you want a PR? I'm not sure I can't even use the library but I made the changes first, thought about it later. So I can send if you want them.

**Comment by ereator** [comment]
Yes, please make a pull request, I will test whether all demos and unit test running and merge your changes into the master. Thank you very much for you contribution.

**Comment by TechnikEmpire** [comment]
Unit tests pass but I didn't try demos. Will submit a PR today.

**Comment by TechnikEmpire** [comment]
Probably submitted and merged so I'm closing.
