### ISSUE TITLE
Initialization error in make: Cause: 3rdparty/densecrf/edgePotentialPotts.cpp

### ISSUE THREAD

**Issue by aliyasineser** [Project-10/DGM#17]
In DGM/3rdparty/densecrf/edgePotentialPotts.cpp, I got the error:
error: invalid initialization of non-const reference of type 'cv::Mat&' from an rvalue of type 'cv::Mat'

Cause of line 34:
https://github.com/Project-10/DGM/blob/257036357b1a18f4decab0aa472f9388f9400828/3rdparty/densecrf/edgePotentialPotts.cpp#L34

Odroid C2, installed OpenCV 3.2.0 but I changed cmake. I commented:
https://github.com/Project-10/DGM/blob/257036357b1a18f4decab0aa472f9388f9400828/CMakeLists.txt#L14
And I used OpenCV 3:
https://github.com/Project-10/DGM/blob/257036357b1a18f4decab0aa472f9388f9400828/CMakeLists.txt#L15

**Comment by aliyasineser** [comment]
To solve:
https://github.com/Project-10/DGM/blob/257036357b1a18f4decab0aa472f9388f9400828/3rdparty/densecrf/edgePotentialPotts.cpp#L34
Change the code:
`m_function(temp.row(n), temp.row(n));`
Instead, do this:
`Mat param1 = temp.row(n);
Mat param2 = temp.row(n);
m_function(param1, param2);`

This is worked for me. But I don't know which part of the library works denseCRF's this par of the code so I need an approval.

**Comment by ereator** [comment]
@aliyasineser Thank you for reporting this bug and proposing a fix! I have also found with clang yesterday. Let me check one more time and fix it with the next commit.

**Comment by aliyasineser** [comment]
Worked like a charm! Thanks!
