### ISSUE TITLE
Error in make: ‘isnan’ was not declared in this scope

### ISSUE THREAD

**Issue by aliyasineser** [Project-10/DGM#18]
This error comes in various parts in make. Is there a spesific flag to show isnan is an std function?

**Comment by aliyasineser** [comment]
To solve issue I added a define:
`#define isnan std::isnan`
It can solve the problem. There are some source files that both uses isnan and std::isnan. To solve it, I added define and remove std::isnan and added only isnan. So define part won't make it std::std::isnan.

**Comment by aliyasineser** [comment]
Problem solved, no issues happening while installing the library.

**Comment by bfdmetu** [comment]
> #define isnan std::isnan

Thank you. 

Solve my problem
