### ISSUE TITLE
can't use class CEdgeModelPotts explicitly

### ISSUE THREAD

**Issue by Ericgeese** [Project-10/DGM#25]
DGM: 1.7.0 && OpenCV 4.0.0 && Ubuntu 18.04 && Compiler g++

First, I can't use **CEdgeModelPotts** because it's unidentified;
Next, I find "DGM.h" doesn't include "EdgeModelPotts.h" so I include it explicitly.
But it reports 

`In file included from /usr/local/include/DGM.h:5:0,
                 from /home/base/Desktop/XX.cpp:2:
/usr/local/include/DGM/EdgeModelPotts.h:6:10: fatal error: permutohedral/permutohedral.h: No such file or directory
 #include "permutohedral/permutohedral.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
`
I'm now confused. Is it a bug? I expect to use **CEdgeModelPotts** directly in my code.

**Comment by ereator** [comment]
Hello @Ericgeese , 
Thank you for committing this issue.
File permutohedral.h can be found in DGM/3rdparty/permutohedral/ folder. I think you need to add additional include directory flag with this path when compiling you project. Please let me know if this hot fix helps.

**Comment by Ericgeese** [comment]
Thanks, I handle it.
