### ISSUE TITLE
Train dense models (CRF) on multiple images

### ISSUE THREAD

**Issue by advanpix** [Project-10/DGM#28]
Thank you for your outstanding work on the library. 

This not a bug report, just a question.

The training example shows the case when only one image is used for training: http://research.project-10.de/dgmdoc/a01846.html

Is there possibility to train the dense model using several (or many) training images with ground truth. Similar to what we do in training neural network. I have checked the original code DenseCRF, and several derivative projects - no such functionality included. Is it possible as all?

**Comment by yuliu** [comment]
Yes it should be possible and requires altering DGM framework a little.

I had altered the framework year ago but can't collect the memory on how I did that ATM.

**Comment by ereator** [comment]
Yes it is possible and even without altering DGM framework.
Simply call `nodeTrainer->addFeatureVecs(train_fv, train_gt);` multiple times _e.g._ in a loop for multiple images (with new `train_fv `and `train_gt`). When you are done adding all the feature vectors, call et the end `nodeTrainer->train();`
That's it.

**Comment by advanpix** [comment]
Great! Will try this.
Thank you for your quick and helpful reply!
