### ISSUE TITLE
2D PDF not used in CTrainNodeBayes

### ISSUE THREAD

**Issue by julien-mille** [Project-10/DGM#31]
In CTrainNodeBayes, the 2D PDF special case is handled in addFeatureVec(const cv::Mat &, byte), but it is not taken into account in calculateNodePotentials(const cv::Mat &, cv::Mat &, cv::Mat &).

CTrainNodeBayes::getPDF2D(byte) is called nowhere.

**Comment by ereator** [comment]
Yes, everything is correct.
The deal is that the Bayes model considers all features to be independent and thus it is sufficient and enough to use only 1D PDFs.
The 2D PDF is estimated only for one special case - when the training data has 2 features. It is not used in the classification process. The only reason of adding 2D PDF into the class was to estimate real distribution of features (_e.g._ ground-truth distribution) for the tutorial: [Training of a random model](http://project-10.de/forum/viewtopic.php?f=31&t=954&sid=9bf9ff3909286210b85eacba4509fcad) (depicted on the first post)

**Comment by julien-mille** [comment]
Ok, sounds good.
