### ISSUE TITLE
Training of pairwise potentials of a dense CRF

### ISSUE THREAD

**Issue by I3aer** [Project-10/DGM#33]
Hi,

Given pairwise potentials for a dense CRF (DCRF) I want to know if it is available to train bilateral and smoothing kernel parameters. I've checked the "Demo Dense" but as far as I understand the training learns unary node potentials. In "Demo Train", the edge trainer learns edge potentials between any two nodes of a bidirectional graph. The for loops to add edge vectors in Demo Train process only nodes (x,y),(x,y-1),(x-1,y), where x is the row index and y is the height index of an image/matrix. However, in a dense graph all nodes (pixels) are connected to each other. Also, in Demo Train the x and y indices start from 1. Then, the loops skip some edges such as those between the nodes in the first row indexed by x=0, e.g., (0,0) and (1,0). Briefly, I could not understand the adjacency for the class "CGraphPairwiseExt". However, I think I should write such a loop to add edge vectors between a selected pixel and the others to train potentials for a DCRF. Can you please help me to understand how to use training DGM module for DCRFs?

Thank you!

**Comment by ereator** [comment]
Hi.
If I understand the question correctly, you wish to train the Bilateral Edge Model for the dense graph. You are right, that there is no training for that. (It is possible to train pairwise edge potentials, but they can't be used with the dense graph).

However, I think I can give you a hint how to tune the Bilateral Edge Model for your data. First of all, the Bilateral Edge Model is added to the graph via method `void addBilateralEdgeModel(...)`. This method has a number of parameters and it is possible to train these parameters. Please see the [Demo Param Estimation](https://research.project-10.de/dgmdoc/a01850.html) for the details how to do that.

Please let me know if this answers your question.

**Comment by I3aer** [comment]
Hi,

Thanks for your answer. I will check that demo to understand how to train parameters of bilateral kernels.
