### ISSUE TITLE
Compiling on MacOS

### ISSUE THREAD

**Issue by usptact** [Project-10/DGM#9]
When running CMake, all dependencies seem to be satisfied. Running make from the build directory complains about "Zi" directory not being found. What is this directory?

```
Scanning dependencies of target DGM
[  1%] Building CXX object modules/DGM/CMakeFiles/DGM.dir/AveragePrecision.cpp.o
clang: error: no such file or directory: '/Zi'
make[2]: *** [modules/DGM/CMakeFiles/DGM.dir/AveragePrecision.cpp.o] Error 1
make[1]: *** [modules/DGM/CMakeFiles/DGM.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by ereator** [comment]
/Zi is auxiliary flag, needed for Visual Studio to produce debug information. MSDN says:
> Produces a program database (PDB) that contains type information and symbolic debugging information for use with the debugger. The symbolic debugging information includes the names and types of variables, as well as functions and line numbers.

Actually the DGM library was never build on MacOS. However, Visual Studio exists also for Mac: https://www.visualstudio.com/ru/vs/visual-studio-mac/ 
Alternatively, the DGM CMakeLists.txt files must be adopted for MacOS.
